name: Actions Remove Files
on:
  repository_dispatch:
  workflow_dispatch:      
    inputs:
      repos:
        description: "Select the Repositories"
        required: false
        default: "all"
        type: choice
        options:         
          - 3wlh.github.io
          - OpenWrt
          - Script
          - Yi_Source
          - Source
          - Actions-Build_ImmortalWrt
          - OpenWrt_Packages

jobs:
  merge:
    name: Remove ${{ inputs.repos }} Files
    runs-on: ubuntu-latest
    steps:
    - name: Install Package
      run : |
        # 安装软件
        sudo apt update > /dev/null 2>&1 && \
        sudo apt install git-filter-repo
        
    - name: Set Git identity
      run : |
        # 初始化数据
        sudo timedatectl set-timezone "Asia/Shanghai"
        git config --global user.email "3wlh-actions[bot]@users.noreply.github.com"
        git config --global user.name "3wlh-actions[bot]"
        echo "repo_dir=$(mktemp -d)" >> $GITHUB_ENV
        sudo apt install git-filter-repo

    - name: Git Clone Repositories
      working-directory: ${{ env.repo_dir }}
      run : |
        git clone https://3wlh:${{ secrets.TOKEN_3WLH }}@github.com/3wlh/${{ inputs.repos }} $(pwd)
        ls
    
    - name: Git Remove Files
      working-directory: ${{ env.repo_dir }}
      run : |
        # 删除历史中所有当前不存在的文件
        #git ls-files > /tmp/keep-files.txt
        git filter-repo --invert-paths --paths-from-file <(git ls-files) --force
        # 获取当前默认分支
        branch=$(git rev-parse --abbrev-ref HEAD)
        # 清理优化Git仓库
        git gc --prune=now --aggressive
        # 强制提交到远程仓库
        git push --force origin ${branch}

    - name: Git Remove Files Tow
      if: false
      working-directory: ${{ env.repo_dir }}
      run : |
        # 删除历史中所有当前不存在的文件
        git ls-files > /tmp/keep-files.txt
        git filter-branch --force --index-filter \
        "git rm --cached --ignore-unmatch $(cat /tmp/keep-files.txt | grep -v '^$' | tr '\n' ' ')" \
        --prune-empty --tag-name-filter cat -- --all
        # 获取当前默认分支
        branch=$(git rev-parse --abbrev-ref HEAD)
        # 提交更改
        git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
        # 清理优化Git仓库
        git gc --prune=now --aggressive
        # 强制提交到远程仓库
        git push --force origin ${branch}