name: Call GitHub Push CNB

on:
  workflow_call:
    inputs:
      pull_repo:
        type: string
      push_repo:
        type: string
        
jobs:
  jod_Call:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: init
        run : |
          # ✅初始化数据
          sudo timedatectl set-timezone "Asia/Shanghai"
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          echo "cnb_repo=$(mktemp -d)" >> $GITHUB_ENV
          git config --global user.name "3wlh"
          git config --global user.email "3wlh@3wlh.cn"
          git config --global core.quotepath false

      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: ${{ inputs.pull_repo }}
          token: ${{ secrets.TOKEN_GITHUB }} 
      
      - name: Git Clone Repositories
        working-directory: ${{ env.cnb_repo }}
        env:
          url: https://cnb:${{ secrets.TOKEN_CNB }}@cnb.cool/${{ inputs.push_repo }}
        run : |
          # ✅克隆同步仓库
          git clone ${url} $(pwd)
      
      - name: Git Clone Repositories
        run : |
          # ✅复制文件
          rm -fr .git .github
          cp -r $(pwd)/* ${{ env.cnb_repo }}/
      
      - name: Repository Commits
        working-directory: ${{ env.cnb_repo }}
        run: |
          # ✅Git提交一次仓库
          git add -A >/dev/null 2>&1
          git commit -m "${COMMIT_MESSAGE:-Reset commit history} - $(date +%Y-%m-%d\ %H:%M:%S)" || true
          git gc --prune=now --aggressive
      
      - name: Git Remove Files
        uses: 3wlh/actions/git/remove-files@main
        env:
          url: https://cnb:${{ secrets.TOKEN_CNB }}@cnb.cool/${{ inputs.push_repo }}
        with:
          repo_url: ${url}
          repo_path: ${{ env.cnb_repo }}
      
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          keep_minimum_runs: 3