name: Call GitHub Push CNB

on:
  workflow_call:
    inputs:
      user:
        type: string
      repository:
          type: string
      
env:
  repo_url: https://${{ inputs.user }}:${{ secrets.TOKEN_CNB }}@cnb.cool/${{ inputs.user }}/${{ inputs.repository }}
        
jobs:
  jod_Call:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: init
        run : |
          # ✅初始化数据
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "repo_dir=$(mktemp -d)" >> $GITHUB_ENV
          git config --global user.name "3wlh"
          git config --global user.email "3wlh@3wlh.cn"

      - name: Checkout
        uses: actions/checkout@main

      - name: Git Clone Repositories
        run : |
          # ✅复制文件
          rm -fr .git .github
          cp -r $(pwd)/* ${{ env.repo_dir }}/
      
      - name: Repository Remove Commits
        working-directory: ${{ env.repo_dir }}
        run: |
          # ✅Git提交一次仓库
          git add -A >/dev/null 2>&1
          git commit -m "${COMMIT_MESSAGE:-Reset commit history} - $(date +%Y-%m-%d\ %H:%M:%S)" || true
          git gc --prune=now --aggressive
      
      - name: Git Remove Files
        uses: 3wlh/actions/git/remove-files@main
        with:
          repo_url: ${{ env.repo_url }}
          repo_path: ${{ env.repo_dir }}