name: cs

on:
  workflow_dispatch:
    
jobs:
  jods_Actions:
    name: cs
    runs-on: ubuntu-latest
    steps:
      - name: cs
        run: |
          mkdir -pm 755 /tmp/cs
          echo "CS" > /tmp/cs/CS.TXT
          echo "CS2" > /tmp/cs/CS2.TXT
          ls /tmp/cs/
      
      - name: cs
        uses: 3wlh/actions/CNB/upload-releases@main
        with:
          repository: 3wlh/OpenWrt_Packages
          token: ${{ secrets.TOKEN_CND }}
          tag_name: "GitHub-Actions_v1.0.0"
          body: |
            ## 测试
            - 上传时间：`${{ env.BUILD_TIME }}`
          files: /tmp/cs/*
          
      - name: Delete Releases
        uses: 3wlh/actions/CNB/delete-releases@main
        with:
          token: ${{ secrets.TOKEN_CNB }}
          tag_name: "GitHub-Actions_*" 